# Generated by Django 5.0 on 2023-12-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='student_pics')),
                ('class_level', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
